name: teip-gbm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pyyaml
  - pip:
      - torch
      - pytorch-lightning
      - omegaconf
      - streamlit
